version: "3"

services:
  lb:
    image: haproxy
    restart: always
    depends_on:
      - nodeapp1
      - nodeapp2
    ports:
      - '8080:8080'
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  nodeapp1:
    image: nodeapp
    depends_on: 
      - mongo-db
    restart: always
    environment:
      - MONGO_DB_HOST=mongo-db
      - JWT_SECRET=aaa
      - APPID=1111
    # ports:
    #   - '4000:3000'

  nodeapp2:
    image: nodeapp
    depends_on: 
      - mongo-db
    restart: always
    environment:
      - MONGO_DB_HOST=mongo-db
      - JWT_SECRET=aaa
      - APPID=2222
    # ports:
    #   - '4000:3000'

  mongo-db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: