version: "3"

services:
  nodeapp:
    image: nodeapp
    environment:
      - MONGO_DB_HOST=mongo-db
      - JWT_SECRET=aaa
    ports:
      - '3000:3000'

  mongo-db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: