@baseUrl = http://localhost:3000/auth

POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "john4@gmail.com",
  "password": "1234"
}

###

POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "john4@gmail.com",
  "password": "1234"
}