@baseUrl = http://localhost:3000

GET {{baseUrl}}

###

GET {{baseUrl}}/employees

###

GET {{baseUrl}}/employees/61a30284b1d1deae8477beb9

###

DELETE {{baseUrl}}/employees/61a2f960bbb5c116801895aa

###

POST {{baseUrl}}/employees
Content-Type: application/json
jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTMyMDM3MmFmOWFjMzlmMjBkNWY1MSIsImVtYWlsIjoiam9objRAZ21haWwuY29tIiwiaWF0IjoxNjM4MDgwNTk4fQ.QdGmTT0bgZPr8MED_L0bzip2-W2gVKmAaHl1DjcMct4

{
  "name":"John",
  "lastName":"Doe",
  "email":"Kaleigh.Gutkowski63@hotmail.com",
  "age":43,
  "salary":40038,
  "role":"Manager"
}

###

PUT {{baseUrl}}/employees/61a30284b1d1deae8477beb9
Content-Type: application/json

{
  "name": "new 3 John",
  "lastName": "new last name"
}
