@baseUrl = http://localhost:3000

GET {{baseUrl}}

###

GET {{baseUrl}}/employees

###

GET {{baseUrl}}/employees/61a30284b1d1deae8477beb9

###

DELETE {{baseUrl}}/employees/61a2f960bbb5c116801895aa

###

POST {{baseUrl}}/employees
Content-Type: application/json

{
  "name":"John",
  "lastName":"Doe",
  "email":"Kaleigh.Gutkowski63@hotmail.com",
  "age":43,
  "salary":40038,
  "role":"Manager"
}